name: Sync mati-capacitor
on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout steps
        uses: actions/checkout@v2.3.4
      - name: Update Docs
        run: npx rdme docs ./docs --key=${{secrets.METAMAP_KEY}} --version 1.2
